# List the (additional, Accuracy is always included) metrics used by the downstream datasets and their chance values
# The *first* metric will be used to generate plots.
# Specify the chance level of the metric as associated value, if not specified, assumed to be 0.5

dreamer_valence:
  - bac: 0.2

dreamer_arousal:
  - bac: 0.2

dreamer_dominance:
  - bac: 0.2

seed_1:
  - Accuracy: 0.33

seed_2:
  - Accuracy: 0.33

seed_3:
  - Accuracy: 0.33

mmidb:
  - bac

bci_iv_2a:
  - Accuracy: 0.25

ern:
  - auroc

erpbci:
  - auroc

sleep-edf:
  - bac: 0.2


